name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok' --quiet"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5
          --health-start-period 40s

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          npm run prepare

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --max-warnings=0

      - name: Run tests
        run: npm test
        env:
          MONGODB_URI: mongodb://root:example@localhost:27017/report-processing-test?authSource=admin
          EMAIL_HOST: smtp.gmail.com
          EMAIL_PORT: 587
          EMAIL_USER: test@example.com
          EMAIL_PASSWORD: test-password
          ALLOWED_SENDERS: test@example.com
          CHECK_INTERVAL: 300000

      - name: Build project
        run: npm run build
        env:
          MONGODB_URI: mongodb://root:example@localhost:27017/report-processing-test?authSource=admin
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }} 